import type { FaqItem } from '@/lib/seo';
import type { Locale } from '@/i18n/config';

export interface SiteFaqs {
  home: FaqItem[];
  answers: FaqItem[];
  perPage: FaqItem[];
  lookup: FaqItem[];
}

const en: SiteFaqs = {
  home: [
    {
      question: 'Is this really free?',
      answer:
        'Yes. Every puzzle and every PDF is free, with no account, no email address, no trial and no watermark on the printed sheets. There is no paid tier holding back the good puzzles — the expert grids are the same generator as the easy ones, just with more clues removed.',
    },
    {
      question: 'Can I get the answers too?',
      answer:
        'Two ways. Tick "Include answers" before you generate and the PDF gets a second section after the puzzles, laid out in the same order, with each solution labelled by its puzzle code — useful if you are printing for a class and want to keep those pages back. Or leave it unticked and look a solution up later on the answer lookup page using the code printed under the grid.',
    },
    {
      question: 'What paper size does it print on?',
      answer:
        'A4 or US Letter — pick whichever matches your printer before you generate. The margins are set at 16 mm on all sides, comfortably inside the non-printable edge of any home or office printer, so nothing gets clipped and you do not need to scale the pages down.',
    },
    {
      question: 'How many puzzles can I put on one page?',
      answer:
        'One, two, four or six. One per page gives a large grid that is easy on the eyes and easy to write in. Two per page is the everyday choice. Four and six per page are for when you want a stack of puzzles for a trip or a classroom and want to spend less paper doing it.',
    },
    {
      question: 'Does every puzzle have exactly one solution?',
      answer:
        'Yes, and that is checked rather than assumed. The generator starts from a completed grid and removes one clue at a time, running a solver after each removal. If taking a clue out would leave the puzzle with more than one possible answer, that clue is put straight back. A puzzle only reaches your PDF once it has been verified to have a single solution.',
    },
    {
      question: 'Do my puzzles get uploaded anywhere?',
      answer:
        'No. The puzzles are generated by JavaScript running in your browser and the PDF is assembled there too. Nothing about your run is sent to a server, which is also why the download is instant and why the site works after the page has loaded even if you go offline.',
    },
    {
      question: 'How long does a big batch take?',
      answer:
        'A few seconds for most runs. Sixty easy puzzles take longer than six, and expert puzzles take longer than easy ones because the solver has more work to do at each removal step. Generation runs on a background thread, so the page stays responsive and a progress line tells you which puzzle is being set.',
    },
    {
      question: 'Can I use these puzzles in a classroom or a newsletter?',
      answer:
        'Yes. Print them for your class, your care home, your commute or your parish newsletter. The puzzles are machine-generated and we make no ownership claim over the grids you produce — you do not need to ask, credit or pay.',
    },
  ],
  answers: [
    {
      question: 'Where do the answers appear in the PDF?',
      answer:
        'In their own section after all the puzzle pages, never on the same sheet as the puzzle they solve. That way you can hand out the puzzle pages on their own and keep the key back, and nobody catches an accidental glimpse of the grid they are working on.',
    },
    {
      question: 'How do I match a solution to its puzzle?',
      answer:
        'Every puzzle is printed with a six-character code under its grid, alongside its difficulty and clue count. The matching solution carries the same code, so "#K7M2A9 solution" is the answer to puzzle #K7M2A9 no matter how you shuffle the pages.',
    },
    {
      question: 'Can I print the puzzles without the answer key?',
      answer:
        'Yes — leave "Include answers" unticked and the PDF contains puzzle pages only. That is the default everywhere except this page. You can also generate once with the answers included and simply print the first half of the document, since the answer section always comes last.',
    },
    {
      question: 'Are the answers guaranteed correct?',
      answer:
        'The solution is not worked out after the fact — it is where the puzzle came from. The generator builds a complete valid grid first, then removes clues from it, so the printed answer key is the original grid. And because a clue is only removed when the puzzle still solves uniquely, that grid is the only answer that fits.',
    },
    {
      question: 'Can I get the answer key at a bigger size?',
      answer:
        'Set puzzles per page to 1 or 2. The key uses exactly the same layout as the puzzle section, so a one-per-page run gives you full-size solution grids that are easy to check at a glance.',
    },
  ],
  perPage: [
    {
      question: 'Are four-per-page grids big enough to write in?',
      answer:
        'On A4 or Letter each grid comes out around 8 cm square, so every cell is roughly 9 mm — about the size of a cell in a newspaper sudoku. It is comfortable with a pencil or a fine pen. If you like to write candidate numbers in the corners of cells, two per page will suit you better.',
    },
    {
      question: 'How many puzzles do I get per sheet of paper?',
      answer:
        'Four per side, so eight per sheet if your printer does double-sided. A run of 24 puzzles at four per page is six sheets of puzzles, or three if you print both sides — and another six pages if you include the answer key.',
    },
    {
      question: 'Does the answer key also print four per page?',
      answer:
        'Yes. The key mirrors whatever layout you chose for the puzzles, so a four-per-page run gives you four-per-page solutions in the same order.',
    },
    {
      question: 'What is the best layout for saving paper?',
      answer:
        'Six per page in two columns of three is the densest layout on offer. It is a good fit for easy and medium puzzles where you are not writing many notes in the margins; for hard and expert grids most people prefer four per page or fewer.',
    },
  ],
  lookup: [
    {
      question: 'Where do I find the puzzle code?',
      answer:
        'It is printed directly under the grid, just left of the difficulty. Six characters after a hash, like #K7M2A9. Every puzzle on every sheet carries its own.',
    },
    {
      question: 'How can it know the answer without storing my puzzle?',
      answer:
        'Because the code is not a reference to a stored puzzle — it is the recipe for one. The generator turns a code into a grid by a fixed procedure with no randomness left in it, so feeding the same code back in rebuilds exactly the same puzzle, and its solution, from scratch. Nothing was ever uploaded and nothing needed to be kept.',
    },
    {
      question: 'Does this work for a sheet I printed months ago?',
      answer:
        'Yes. There is no expiry and no database to go stale — the code is all that is needed. A sheet found at the back of a drawer in five years will still look up, as long as the code is legible.',
    },
    {
      question: 'It says the code is not one we could have printed. What now?',
      answer:
        'Almost always a misread character. The codes never contain the letters I, L, O or U, precisely so they cannot be confused with 1 and 0 — so if you read one of those, try the digit instead. The check built into every code means a wrong entry is rejected rather than quietly returning somebody else’s puzzle.',
    },
    {
      question: 'Can I still get the answers printed in the PDF?',
      answer:
        'Yes, that has not gone anywhere. Tick "Include answers" in the generator and the solutions come as a section at the back of the document. It is off by default, since most people would rather have a clean set of puzzles and look up the odd answer here. This page is for exactly that.',
    },
    {
      question: 'Can I link straight to a solution?',
      answer:
        'Add the code to the address: /sudoku-answers?code=K7M2A9 opens with that puzzle already worked out. Handy if you are setting puzzles for other people and want to hand them the answer separately.',
    },
  ],
};

const de: SiteFaqs = {
  home: [
    {
      question: 'Ist das wirklich kostenlos?',
      answer:
        'Ja. Jedes Rätsel und jedes PDF ist kostenlos, ohne Konto, ohne E-Mail-Adresse, ohne Testphase und ohne Wasserzeichen auf den gedruckten Blättern. Es gibt keine kostenpflichtige Stufe, die die guten Rätsel zurückhält — die Experten-Raster kommen aus demselben Generator wie die einfachen, nur mit mehr entfernten Hinweisen.',
    },
    {
      question: 'Bekomme ich auch die Lösungen?',
      answer:
        'Auf zwei Wegen. Hake vor dem Erstellen „Lösungen einschließen“ an, dann bekommt das PDF nach den Rätseln einen zweiten Abschnitt in derselben Reihenfolge, jede Lösung mit ihrem Rätselcode beschriftet — praktisch, wenn du für eine Klasse druckst und diese Seiten zurückhalten willst. Oder lass es abgehakt aus und schlage die Lösung später auf der Lösungssuche-Seite nach, mit dem Code, der unter dem Raster steht.',
    },
    {
      question: 'Auf welches Papierformat wird gedruckt?',
      answer:
        'A4 oder US Letter — wähle vor dem Erstellen, was zu deinem Drucker passt. Die Ränder sind rundum auf 16 mm gesetzt, bequem innerhalb des unbedruckbaren Rands jedes Heim- oder Bürodruckers, sodass nichts abgeschnitten wird und du die Seiten nicht verkleinern musst.',
    },
    {
      question: 'Wie viele Rätsel kann ich auf eine Seite packen?',
      answer:
        'Eins, zwei, vier oder sechs. Eins pro Seite ergibt ein großes, augenschonendes Raster, in das man bequem schreiben kann. Zwei pro Seite ist die Alltagswahl. Vier und sechs pro Seite eignen sich, wenn du einen Stapel Rätsel für eine Reise oder eine Klasse willst und dabei Papier sparen möchtest.',
    },
    {
      question: 'Hat jedes Rätsel wirklich genau eine Lösung?',
      answer:
        'Ja, und das wird geprüft statt nur angenommen. Der Generator startet mit einem vollständigen Raster und entfernt nacheinander einzelne Hinweise, wobei nach jeder Entfernung ein Lösungsalgorithmus läuft. Würde das Entfernen eines Hinweises dem Rätsel mehr als eine mögliche Lösung geben, wird dieser Hinweis sofort wieder eingesetzt. Ein Rätsel landet erst in deinem PDF, wenn geprüft wurde, dass es genau eine Lösung hat.',
    },
    {
      question: 'Werden meine Rätsel irgendwohin hochgeladen?',
      answer:
        'Nein. Die Rätsel werden von JavaScript erzeugt, das in deinem Browser läuft, und auch das PDF wird dort zusammengesetzt. Nichts von deiner Auflage wird an einen Server geschickt — deshalb ist der Download sofort da, und die Seite funktioniert weiter, selbst wenn du offline gehst, nachdem sie geladen wurde.',
    },
    {
      question: 'Wie lange dauert eine große Auflage?',
      answer:
        'Bei den meisten Auflagen nur wenige Sekunden. Sechzig einfache Rätsel dauern länger als sechs, und Experten-Rätsel dauern länger als einfache, weil der Lösungsalgorithmus bei jedem Entfernungsschritt mehr zu tun hat. Die Erstellung läuft in einem Hintergrund-Thread, sodass die Seite reagibel bleibt und eine Fortschrittsanzeige zeigt, welches Rätsel gerade gesetzt wird.',
    },
    {
      question: 'Darf ich diese Rätsel in einer Klasse oder einem Newsletter verwenden?',
      answer:
        'Ja. Drucke sie für deine Klasse, dein Pflegeheim, deinen Arbeitsweg oder den Gemeindebrief. Die Rätsel werden maschinell erzeugt, und wir erheben keinen Eigentumsanspruch auf die von dir erzeugten Raster — du musst weder fragen noch nennen noch bezahlen.',
    },
  ],
  answers: [
    {
      question: 'Wo stehen die Lösungen im PDF?',
      answer:
        'In einem eigenen Abschnitt nach allen Rätselseiten, nie auf demselben Blatt wie das dazugehörige Rätsel. So kannst du die Rätselseiten allein weitergeben und den Lösungsteil zurückhalten, und niemand erhascht versehentlich einen Blick auf das Raster, an dem er gerade arbeitet.',
    },
    {
      question: 'Wie ordne ich eine Lösung dem richtigen Rätsel zu?',
      answer:
        'Jedes Rätsel trägt einen sechsstelligen Code unter dem Raster, zusammen mit Schwierigkeit und Anzahl der Hinweise. Die passende Lösung trägt denselben Code, sodass „Lösung zu #K7M2A9“ die Antwort auf Rätsel #K7M2A9 ist, egal wie du die Seiten durchmischst.',
    },
    {
      question: 'Kann ich die Rätsel ohne Lösungsschlüssel drucken?',
      answer:
        'Ja — lass „Lösungen einschließen“ abgehakt, dann enthält das PDF nur Rätselseiten. Das ist überall die Voreinstellung außer auf dieser Seite. Du kannst auch einmal mit eingeschlossenen Lösungen erstellen und einfach nur die erste Hälfte des Dokuments drucken, da der Lösungsteil immer zuletzt kommt.',
    },
    {
      question: 'Sind die Lösungen garantiert richtig?',
      answer:
        'Die Lösung wird nicht nachträglich errechnet — sie ist der Ursprung des Rätsels. Der Generator baut zuerst ein vollständiges, gültiges Raster und entfernt dann Hinweise daraus, sodass der gedruckte Lösungsschlüssel das ursprüngliche Raster ist. Und weil ein Hinweis nur entfernt wird, wenn das Rätsel weiterhin eindeutig lösbar bleibt, ist dieses Raster die einzige passende Lösung.',
    },
    {
      question: 'Kann ich den Lösungsschlüssel größer bekommen?',
      answer:
        'Stelle Rätsel pro Seite auf 1 oder 2. Der Lösungsschlüssel verwendet genau dasselbe Layout wie der Rätselteil, sodass eine Auflage mit einem Rätsel pro Seite auch Lösungsraster in voller Größe liefert, die sich auf einen Blick prüfen lassen.',
    },
  ],
  perPage: [
    {
      question: 'Sind Raster mit vier pro Seite groß genug zum Reinschreiben?',
      answer:
        'Auf A4 oder Letter wird jedes Raster etwa 8 cm im Quadrat, jedes Feld also rund 9 mm — etwa so groß wie ein Feld in einem Zeitungs-Sudoku. Mit Bleistift oder einem feinen Stift ist das gut machbar. Wenn du gerne Kandidatenzahlen in die Feldecken schreibst, passen zwei pro Seite besser zu dir.',
    },
    {
      question: 'Wie viele Rätsel bekomme ich pro Blatt Papier?',
      answer:
        'Vier pro Seite, also acht pro Blatt, wenn dein Drucker beidseitig druckt. Eine Auflage von 24 Rätseln mit vier pro Seite sind sechs Rätselblätter, oder drei bei beidseitigem Druck — plus sechs weitere Seiten, wenn du den Lösungsschlüssel dazu nimmst.',
    },
    {
      question: 'Wird der Lösungsschlüssel auch mit vier pro Seite gedruckt?',
      answer:
        'Ja. Der Lösungsschlüssel übernimmt genau das Layout, das du für die Rätsel gewählt hast, sodass eine Auflage mit vier pro Seite auch die Lösungen zu viert pro Seite in derselben Reihenfolge liefert.',
    },
    {
      question: 'Welches Layout spart am meisten Papier?',
      answer:
        'Sechs pro Seite in zwei Spalten zu je drei ist das dichteste angebotene Layout. Es passt gut zu einfachen und mittelschweren Rätseln, bei denen du nicht viele Notizen an den Rand schreibst; für schwere und Experten-Raster bevorzugen die meisten vier pro Seite oder weniger.',
    },
  ],
  lookup: [
    {
      question: 'Wo finde ich den Rätselcode?',
      answer:
        'Er steht direkt unter dem Raster, links neben der Schwierigkeit. Sechs Zeichen nach einer Raute, zum Beispiel #K7M2A9. Jedes Rätsel auf jedem Blatt trägt seinen eigenen.',
    },
    {
      question: 'Wie kann die Seite die Lösung kennen, ohne mein Rätsel zu speichern?',
      answer:
        'Weil der Code kein Verweis auf ein gespeichertes Rätsel ist — er ist das Rezept dafür. Der Generator verwandelt einen Code nach einem festen Verfahren ohne verbleibenden Zufall in ein Raster, sodass derselbe Code, erneut eingegeben, genau dasselbe Rätsel samt Lösung von Grund auf neu erzeugt. Es wurde nie etwas hochgeladen, und es musste nichts gespeichert werden.',
    },
    {
      question: 'Funktioniert das auch für ein Blatt, das ich vor Monaten gedruckt habe?',
      answer:
        'Ja. Es gibt kein Ablaufdatum und keine Datenbank, die veralten könnte — nötig ist nur der Code. Ein Blatt, das in fünf Jahren hinten in einer Schublade auftaucht, lässt sich immer noch nachschlagen, solange der Code lesbar ist.',
    },
    {
      question: 'Es heißt, der Code sei keiner, den wir hätten ausgeben können. Was jetzt?',
      answer:
        'Fast immer ein falsch gelesenes Zeichen. Die Codes enthalten nie die Buchstaben I, L, O oder U, genau damit sie nicht mit 1 und 0 verwechselt werden — liest du also einen davon, probiere stattdessen die Ziffer. Die in jeden Code eingebaute Prüfung sorgt dafür, dass eine falsche Eingabe abgelehnt wird, statt still das Rätsel von jemand anderem zu liefern.',
    },
    {
      question: 'Kann ich die Lösungen trotzdem im PDF ausdrucken?',
      answer:
        'Ja, das ist weiterhin möglich. Hake im Generator „Lösungen einschließen“ an, dann kommen die Lösungen als Abschnitt ans Ende des Dokuments. Standardmäßig ist das aus, weil die meisten Leute lieber einen sauberen Satz Rätsel haben und hier gelegentlich eine Lösung nachschlagen wollen. Genau dafür ist diese Seite da.',
    },
    {
      question: 'Kann ich direkt auf eine Lösung verlinken?',
      answer:
        'Hänge den Code an die Adresse an: /sudoku-answers?code=K7M2A9 öffnet die Seite mit diesem bereits gelösten Rätsel. Praktisch, wenn du Rätsel für andere zusammenstellst und ihnen die Lösung separat geben willst.',
    },
  ],
};

const fr: SiteFaqs = {
  home: [
    {
      question: 'Est-ce vraiment gratuit ?',
      answer:
        'Oui. Chaque grille et chaque PDF sont gratuits, sans compte, sans adresse e-mail, sans essai et sans filigrane sur les feuilles imprimées. Il n’existe pas de formule payante qui réserverait les meilleures grilles — les grilles expert sortent du même générateur que les faciles, avec simplement plus d’indices retirés.',
    },
    {
      question: 'Puis-je obtenir aussi les solutions ?',
      answer:
        'De deux façons. Cochez « Inclure les solutions » avant de générer, et le PDF recevra une seconde section après les grilles, dans le même ordre, chaque solution étiquetée par le code de sa grille — pratique si vous imprimez pour une classe et voulez garder ces pages à part. Ou laissez la case décochée et retrouvez une solution plus tard sur la page de recherche, avec le code imprimé sous la grille.',
    },
    {
      question: 'Sur quel format de papier cela s’imprime-t-il ?',
      answer:
        'A4 ou US Letter — choisissez celui qui correspond à votre imprimante avant de générer. Les marges sont fixées à 16 mm sur tous les côtés, bien à l’intérieur de la zone non imprimable de n’importe quelle imprimante domestique ou de bureau, si bien que rien n’est coupé et qu’il n’y a pas besoin de réduire les pages.',
    },
    {
      question: 'Combien de grilles puis-je mettre sur une page ?',
      answer:
        'Une, deux, quatre ou six. Une par page donne une grande grille, reposante pour les yeux et facile à remplir. Deux par page est le choix du quotidien. Quatre et six par page conviennent quand vous voulez une pile de grilles pour un voyage ou une classe tout en économisant du papier.',
    },
    {
      question: 'Chaque grille a-t-elle vraiment une seule solution ?',
      answer:
        'Oui, et cela se vérifie plutôt que de se supposer. Le générateur part d’une grille complète et retire les indices un par un, en lançant un solveur après chaque retrait. Si retirer un indice laissait la grille avec plus d’une solution possible, cet indice est immédiatement remis en place. Une grille n’atteint votre PDF qu’une fois vérifiée comme n’ayant qu’une seule solution.',
    },
    {
      question: 'Mes grilles sont-elles envoyées quelque part ?',
      answer:
        'Non. Les grilles sont générées par du JavaScript qui s’exécute dans votre navigateur, et le PDF y est également assemblé. Rien de votre tirage n’est envoyé à un serveur, ce qui explique aussi pourquoi le téléchargement est instantané et pourquoi le site continue de fonctionner même hors connexion une fois la page chargée.',
    },
    {
      question: 'Combien de temps prend un gros lot ?',
      answer:
        'Quelques secondes pour la plupart des tirages. Soixante grilles faciles prennent plus de temps que six, et les grilles expert prennent plus de temps que les faciles car le solveur a plus de travail à chaque étape de retrait. La génération s’exécute sur un fil d’arrière-plan, si bien que la page reste réactive et qu’une ligne de progression indique quelle grille est en cours de composition.',
    },
    {
      question: 'Puis-je utiliser ces grilles en classe ou dans un bulletin ?',
      answer:
        'Oui. Imprimez-les pour votre classe, votre maison de retraite, vos trajets ou le bulletin de votre paroisse. Les grilles sont générées par ordinateur et nous ne revendiquons aucun droit de propriété sur celles que vous produisez — inutile de demander une autorisation, de créditer qui que ce soit ou de payer.',
    },
  ],
  answers: [
    {
      question: 'Où apparaissent les solutions dans le PDF ?',
      answer:
        'Dans leur propre section après toutes les pages de grilles, jamais sur la même feuille que la grille qu’elles résolvent. Vous pouvez ainsi distribuer les pages de grilles seules et garder le corrigé de côté, sans que personne n’aperçoive par mégarde la grille sur laquelle il travaille.',
    },
    {
      question: 'Comment associer une solution à sa grille ?',
      answer:
        'Chaque grille est imprimée avec un code à six caractères sous son plateau, accompagné de sa difficulté et de son nombre d’indices. La solution correspondante porte le même code, si bien que « solution de #K7M2A9 » est la réponse à la grille #K7M2A9, quel que soit l’ordre dans lequel vous mélangez les pages.',
    },
    {
      question: 'Puis-je imprimer les grilles sans le corrigé ?',
      answer:
        'Oui — laissez « Inclure les solutions » décoché, et le PDF ne contiendra que les pages de grilles. C’est le réglage par défaut partout, sauf sur cette page. Vous pouvez aussi générer une fois avec les solutions incluses et n’imprimer que la première moitié du document, puisque la section des solutions arrive toujours en dernier.',
    },
    {
      question: 'Les solutions sont-elles garanties correctes ?',
      answer:
        'La solution n’est pas calculée après coup : c’est elle qui a donné naissance à la grille. Le générateur construit d’abord une grille complète et valide, puis en retire des indices, si bien que le corrigé imprimé est la grille d’origine. Et comme un indice n’est retiré que si la grille reste résoluble de façon unique, cette grille est la seule solution qui convient.',
    },
    {
      question: 'Puis-je obtenir le corrigé en plus grand ?',
      answer:
        'Réglez le nombre de grilles par page sur 1 ou 2. Le corrigé suit exactement la même mise en page que la section des grilles, si bien qu’un tirage à une grille par page vous donne des grilles de solution en taille réelle, faciles à vérifier d’un coup d’œil.',
    },
  ],
  perPage: [
    {
      question: 'Les grilles à quatre par page sont-elles assez grandes pour écrire dedans ?',
      answer:
        'Sur A4 ou Letter, chaque grille fait environ 8 cm de côté, donc chaque case mesure environ 9 mm — à peu près la taille d’une case dans un sudoku de journal. C’est confortable au crayon ou avec un stylo fin. Si vous aimez noter les candidats dans les coins des cases, deux par page vous conviendra mieux.',
    },
    {
      question: 'Combien de grilles obtient-on par feuille de papier ?',
      answer:
        'Quatre par face, donc huit par feuille si votre imprimante imprime recto verso. Un tirage de 24 grilles à quatre par page représente six feuilles de grilles, ou trois en recto verso — plus six pages supplémentaires si vous incluez le corrigé.',
    },
    {
      question: 'Le corrigé s’imprime-t-il aussi à quatre par page ?',
      answer:
        'Oui. Le corrigé reprend exactement la mise en page choisie pour les grilles, si bien qu’un tirage à quatre par page vous donne des solutions à quatre par page, dans le même ordre.',
    },
    {
      question: 'Quelle est la meilleure mise en page pour économiser du papier ?',
      answer:
        'Six par page, en deux colonnes de trois, est la mise en page la plus dense proposée. Elle convient bien aux grilles faciles et moyennes, où vous n’écrivez pas beaucoup de notes en marge ; pour les grilles difficiles et expert, la plupart préfèrent quatre par page ou moins.',
    },
  ],
  lookup: [
    {
      question: 'Où trouver le code de la grille ?',
      answer:
        'Il est imprimé juste sous la grille, à gauche de la difficulté. Six caractères après un dièse, par exemple #K7M2A9. Chaque grille, sur chaque feuille, porte le sien.',
    },
    {
      question: 'Comment le site peut-il connaître la solution sans stocker ma grille ?',
      answer:
        'Parce que le code n’est pas une référence vers une grille stockée : c’est la recette pour en fabriquer une. Le générateur transforme un code en grille selon une procédure fixe, sans aucun hasard restant, si bien que redonner le même code reconstruit exactement la même grille, et sa solution, entièrement à partir de zéro. Rien n’a jamais été envoyé, et rien n’a eu besoin d’être conservé.',
    },
    {
      question: 'Cela fonctionne-t-il pour une feuille imprimée il y a des mois ?',
      answer:
        'Oui. Il n’y a ni expiration ni base de données susceptible de devenir obsolète — seul le code est nécessaire. Une feuille retrouvée au fond d’un tiroir dans cinq ans se retrouvera toujours, tant que le code reste lisible.',
    },
    {
      question: 'Le site indique que ce code n’a pas pu être imprimé par nos soins. Que faire ?',
      answer:
        'Presque toujours un caractère mal lu. Les codes ne contiennent jamais les lettres I, L, O ou U, précisément pour éviter toute confusion avec 1 et 0 — si vous en lisez une, essayez le chiffre à la place. La vérification intégrée à chaque code fait qu’une saisie erronée est rejetée plutôt que de renvoyer discrètement la grille de quelqu’un d’autre.',
    },
    {
      question: 'Puis-je quand même faire imprimer les solutions dans le PDF ?',
      answer:
        'Oui, cela n’a pas disparu. Cochez « Inclure les solutions » dans le générateur, et les solutions arrivent en une section à la fin du document. C’est désactivé par défaut, car la plupart des gens préfèrent un jeu de grilles bien net et venir chercher une solution ici au besoin. C’est exactement à cela que sert cette page.',
    },
    {
      question: 'Puis-je créer un lien direct vers une solution ?',
      answer:
        'Ajoutez le code à l’adresse : /sudoku-answers?code=K7M2A9 ouvre la page avec cette grille déjà résolue. Pratique si vous composez des grilles pour d’autres personnes et voulez leur transmettre la solution séparément.',
    },
  ],
};

const es: SiteFaqs = {
  home: [
    {
      question: '¿Es esto realmente gratis?',
      answer:
        'Sí. Todos los sudokus y todos los PDF son gratis, sin cuenta, sin dirección de correo, sin prueba y sin marca de agua en las hojas impresas. No hay ningún plan de pago que se guarde los mejores sudokus — las cuadrículas expertas salen del mismo generador que las fáciles, solo que con más pistas retiradas.',
    },
    {
      question: '¿También puedo conseguir las soluciones?',
      answer:
        'De dos maneras. Marca «Incluir soluciones» antes de generar y el PDF tendrá una segunda sección después de los sudokus, en el mismo orden, con cada solución identificada por el código de su sudoku — útil si imprimes para una clase y quieres guardarte esas páginas aparte. O déjala sin marcar y busca una solución más tarde en la página de búsqueda, con el código impreso bajo la cuadrícula.',
    },
    {
      question: '¿En qué tamaño de papel imprime?',
      answer:
        'A4 o US Letter — elige el que coincida con tu impresora antes de generar. Los márgenes están fijados en 16 mm por todos los lados, cómodamente dentro del borde no imprimible de cualquier impresora doméstica o de oficina, así que nada se corta y no hace falta reducir las páginas.',
    },
    {
      question: '¿Cuántos sudokus puedo poner en una página?',
      answer:
        'Uno, dos, cuatro o seis. Uno por página da una cuadrícula grande, cómoda para la vista y fácil de rellenar. Dos por página es la opción del día a día. Cuatro y seis por página sirven cuando quieres una pila de sudokus para un viaje o una clase y quieres gastar menos papel al hacerlo.',
    },
    {
      question: '¿Todos los sudokus tienen exactamente una solución?',
      answer:
        'Sí, y eso se comprueba en vez de suponerse. El generador parte de una cuadrícula completa y retira las pistas una a una, ejecutando un solucionador después de cada retirada. Si al quitar una pista el sudoku se quedara con más de una solución posible, esa pista se vuelve a colocar de inmediato. Un sudoku solo llega a tu PDF una vez verificado que tiene una única solución.',
    },
    {
      question: '¿Mis sudokus se suben a algún sitio?',
      answer:
        'No. Los sudokus se generan con JavaScript que se ejecuta en tu navegador, y el PDF también se monta ahí. Nada de tu tirada se envía a ningún servidor, y por eso la descarga es instantánea y la página sigue funcionando aunque te quedes sin conexión después de cargarla.',
    },
    {
      question: '¿Cuánto tarda una tirada grande?',
      answer:
        'Unos segundos en la mayoría de los casos. Sesenta sudokus fáciles tardan más que seis, y los sudokus expertos tardan más que los fáciles porque el solucionador tiene más trabajo en cada paso de retirada. La generación se ejecuta en un hilo en segundo plano, así que la página sigue respondiendo y una línea de progreso indica qué sudoku se está preparando.',
    },
    {
      question: '¿Puedo usar estos sudokus en una clase o en un boletín?',
      answer:
        'Sí. Imprímelos para tu clase, tu residencia, tus trayectos o el boletín de tu parroquia. Los sudokus se generan por ordenador y no reclamamos ningún derecho sobre las cuadrículas que produces — no hace falta pedir permiso, dar crédito ni pagar nada.',
    },
  ],
  answers: [
    {
      question: '¿Dónde aparecen las soluciones en el PDF?',
      answer:
        'En su propia sección después de todas las páginas de sudokus, nunca en la misma hoja que el sudoku que resuelven. Así puedes repartir solo las páginas de sudokus y quedarte con las soluciones aparte, sin que nadie vea sin querer la cuadrícula que está resolviendo.',
    },
    {
      question: '¿Cómo sé qué solución corresponde a qué sudoku?',
      answer:
        'Cada sudoku se imprime con un código de seis caracteres bajo su cuadrícula, junto con su dificultad y su número de pistas. La solución correspondiente lleva el mismo código, así que «solución de #K7M2A9» es la respuesta al sudoku #K7M2A9 sin importar cómo mezcles las páginas.',
    },
    {
      question: '¿Puedo imprimir los sudokus sin las soluciones?',
      answer:
        'Sí — deja «Incluir soluciones» sin marcar y el PDF contendrá solo páginas de sudokus. Esa es la opción por defecto en todas partes menos en esta página. También puedes generar una vez con las soluciones incluidas e imprimir solo la primera mitad del documento, ya que la sección de soluciones siempre va al final.',
    },
    {
      question: '¿Las soluciones están garantizadas como correctas?',
      answer:
        'La solución no se calcula después: es de donde viene el sudoku. El generador construye primero una cuadrícula completa y válida, y luego le retira pistas, así que las soluciones impresas son la cuadrícula original. Y como una pista solo se retira cuando el sudoku sigue teniendo una única solución, esa cuadrícula es la única respuesta posible.',
    },
    {
      question: '¿Puedo conseguir las soluciones en un tamaño más grande?',
      answer:
        'Pon el número de sudokus por página en 1 o 2. Las soluciones usan exactamente el mismo diseño que la sección de sudokus, así que una tirada de uno por página te da cuadrículas de solución a tamaño completo, fáciles de comprobar de un vistazo.',
    },
  ],
  perPage: [
    {
      question: '¿Las cuadrículas de cuatro por página son lo bastante grandes para escribir en ellas?',
      answer:
        'En A4 o Letter, cada cuadrícula sale de unos 8 cm de lado, así que cada casilla mide unos 9 mm — más o menos el tamaño de una casilla de sudoku de periódico. Es cómodo con lápiz o con un bolígrafo fino. Si te gusta anotar candidatos en las esquinas de las casillas, dos por página te vendrá mejor.',
    },
    {
      question: '¿Cuántos sudokus obtengo por hoja de papel?',
      answer:
        'Cuatro por cara, así que ocho por hoja si tu impresora imprime a doble cara. Una tirada de 24 sudokus a cuatro por página son seis hojas de sudokus, o tres si imprimes por ambas caras — y seis páginas más si incluyes las soluciones.',
    },
    {
      question: '¿Las soluciones también se imprimen a cuatro por página?',
      answer:
        'Sí. Las soluciones repiten el mismo diseño que hayas elegido para los sudokus, así que una tirada de cuatro por página te da las soluciones también a cuatro por página, en el mismo orden.',
    },
    {
      question: '¿Cuál es el mejor diseño para ahorrar papel?',
      answer:
        'Seis por página en dos columnas de tres es el diseño más compacto disponible. Va bien con sudokus fáciles y de nivel medio, donde no escribes muchas anotaciones en los márgenes; para cuadrículas difíciles y expertas, la mayoría prefiere cuatro por página o menos.',
    },
  ],
  lookup: [
    {
      question: '¿Dónde encuentro el código del sudoku?',
      answer:
        'Está impreso justo bajo la cuadrícula, a la izquierda de la dificultad. Seis caracteres después de una almohadilla, como #K7M2A9. Cada sudoku, en cada hoja, lleva el suyo propio.',
    },
    {
      question: '¿Cómo puede saber la solución sin guardar mi sudoku?',
      answer:
        'Porque el código no es una referencia a un sudoku guardado — es la receta para crear uno. El generador convierte un código en una cuadrícula siguiendo un procedimiento fijo sin ningún azar de por medio, así que introducir el mismo código otra vez reconstruye exactamente el mismo sudoku, y su solución, desde cero. Nunca se subió nada, y no hizo falta guardar nada.',
    },
    {
      question: '¿Esto funciona con una hoja que imprimí hace meses?',
      answer:
        'Sí. No hay caducidad ni base de datos que pueda quedar obsoleta — solo hace falta el código. Una hoja que aparezca al fondo de un cajón dentro de cinco años se podrá seguir buscando, siempre que el código se pueda leer.',
    },
    {
      question: 'Dice que ese código no es uno que hayamos podido generar. ¿Y ahora qué?',
      answer:
        'Casi siempre es un carácter mal leído. Los códigos nunca contienen las letras I, L, O ni U, precisamente para que no se confundan con 1 y 0 — así que si has leído una de esas letras, prueba con el número. La comprobación integrada en cada código hace que una entrada equivocada se rechace en vez de devolver en silencio el sudoku de otra persona.',
    },
    {
      question: '¿Puedo seguir teniendo las soluciones impresas en el PDF?',
      answer:
        'Sí, eso no ha desaparecido. Marca «Incluir soluciones» en el generador y las soluciones aparecerán como una sección al final del documento. Viene desactivado por defecto, porque la mayoría prefiere tener un conjunto limpio de sudokus y venir aquí a buscar alguna solución suelta. Esta página existe justo para eso.',
    },
    {
      question: '¿Puedo enlazar directamente a una solución?',
      answer:
        'Añade el código a la dirección: /sudoku-answers?code=K7M2A9 abre la página con ese sudoku ya resuelto. Útil si preparas sudokus para otras personas y quieres darles la solución por separado.',
    },
  ],
};

export const SITE_FAQS: Record<Locale, SiteFaqs> = { en, de, fr, es };
