import type { FaqItem } from '@/lib/seo';

/** Homepage FAQ — the questions people actually arrive with. */
export const HOME_FAQS: FaqItem[] = [
  {
    question: 'Is this really free?',
    answer:
      'Yes. Every puzzle and every PDF is free, with no account, no email address, no trial and no watermark on the printed sheets. There is no paid tier holding back the good puzzles — the expert grids are the same generator as the easy ones, just with more clues removed.',
  },
  {
    question: 'Can I get the answers too?',
    answer:
      'Leave "Include an answer key" switched on and the PDF gets a second section after the puzzles, laid out in the same order, with each solution labelled by its puzzle number. If you are printing for a class or a group, print the puzzle pages, keep the key pages, and nobody has to take your word for it.',
  },
  {
    question: 'What paper size does it print on?',
    answer:
      'A4 or US Letter — pick whichever matches your printer before you generate. The margins are set at 16 mm on all sides, comfortably inside the non-printable edge of any home or office printer, so nothing gets clipped and you do not need to scale the pages down.',
  },
  {
    question: 'How many puzzles can I put on one page?',
    answer:
      'One, two, four or six. One per page gives a large grid that is easy on the eyes and easy to write in. Two per page is the everyday choice. Four and six per page are for when you want a stack of puzzles for a trip or a classroom and want to spend less paper doing it.',
  },
  {
    question: 'Does every puzzle have exactly one solution?',
    answer:
      'Yes, and that is checked rather than assumed. The generator starts from a completed grid and removes one clue at a time, running a solver after each removal. If taking a clue out would leave the puzzle with more than one possible answer, that clue is put straight back. A puzzle only reaches your PDF once it has been verified to have a single solution.',
  },
  {
    question: 'Do my puzzles get uploaded anywhere?',
    answer:
      'No. The puzzles are generated by JavaScript running in your browser and the PDF is assembled there too. Nothing about your run is sent to a server, which is also why the download is instant and why the site works after the page has loaded even if you go offline.',
  },
  {
    question: 'How long does a big batch take?',
    answer:
      'A few seconds for most runs. Sixty easy puzzles take longer than six, and expert puzzles take longer than easy ones because the solver has more work to do at each removal step. Generation runs on a background thread, so the page stays responsive and a progress line tells you which puzzle is being set.',
  },
  {
    question: 'Can I use these puzzles in a classroom or a newsletter?',
    answer:
      'Yes. Print them for your class, your care home, your commute or your parish newsletter. The puzzles are machine-generated and we make no ownership claim over the grids you produce — you do not need to ask, credit or pay.',
  },
];

export const ANSWERS_FAQS: FaqItem[] = [
  {
    question: 'Where do the answers appear in the PDF?',
    answer:
      'In their own section after all the puzzle pages, never on the same sheet as the puzzle they solve. That way you can hand out the puzzle pages on their own and keep the key back, and nobody catches an accidental glimpse of the grid they are working on.',
  },
  {
    question: 'How do I match a solution to its puzzle?',
    answer:
      'Every puzzle is printed with a six-digit ID under its grid, alongside its difficulty and clue count. The matching solution carries the same ID, so "#438201 solution" is the answer to puzzle #438201 no matter how you shuffle the pages.',
  },
  {
    question: 'Can I print the puzzles without the answer key?',
    answer:
      'Yes — untick "Include an answer key" and the PDF contains puzzle pages only. You can also generate once with the key included and simply print the first half of the document, since the answer section always comes last.',
  },
  {
    question: 'Are the answers guaranteed correct?',
    answer:
      'The solution is not worked out after the fact — it is where the puzzle came from. The generator builds a complete valid grid first, then removes clues from it, so the printed answer key is the original grid. And because a clue is only removed when the puzzle still solves uniquely, that grid is the only answer that fits.',
  },
  {
    question: 'Can I get the answer key at a bigger size?',
    answer:
      'Set puzzles per page to 1 or 2. The key uses exactly the same layout as the puzzle section, so a one-per-page run gives you full-size solution grids that are easy to check at a glance.',
  },
];

export const PER_PAGE_FAQS: FaqItem[] = [
  {
    question: 'Are four-per-page grids big enough to write in?',
    answer:
      'On A4 or Letter each grid comes out around 8 cm square, so every cell is roughly 9 mm — about the size of a cell in a newspaper sudoku. It is comfortable with a pencil or a fine pen. If you like to write candidate numbers in the corners of cells, two per page will suit you better.',
  },
  {
    question: 'How many puzzles do I get per sheet of paper?',
    answer:
      'Four per side, so eight per sheet if your printer does double-sided. A run of 24 puzzles at four per page is six sheets of puzzles, or three if you print both sides — and another six pages if you include the answer key.',
  },
  {
    question: 'Does the answer key also print four per page?',
    answer:
      'Yes. The key mirrors whatever layout you chose for the puzzles, so a four-per-page run gives you four-per-page solutions in the same order.',
  },
  {
    question: 'What is the best layout for saving paper?',
    answer:
      'Six per page in two columns of three is the densest layout on offer. It is a good fit for easy and medium puzzles where you are not writing many notes in the margins; for hard and expert grids most people prefer four per page or fewer.',
  },
];

export const LOOKUP_FAQS: FaqItem[] = [
  {
    question: 'Where do I find the puzzle code?',
    answer:
      'It is printed directly under the grid, just left of the difficulty. Six characters after a hash, like #K7M2A9. Every puzzle on every sheet carries its own.',
  },
  {
    question: 'How can it know the answer without storing my puzzle?',
    answer:
      'Because the code is not a reference to a stored puzzle — it is the recipe for one. The generator turns a code into a grid by a fixed procedure with no randomness left in it, so feeding the same code back in rebuilds exactly the same puzzle, and its solution, from scratch. Nothing was ever uploaded and nothing needed to be kept.',
  },
  {
    question: 'Does this work for a sheet I printed months ago?',
    answer:
      'Yes. There is no expiry and no database to go stale — the code is all that is needed. A sheet found at the back of a drawer in five years will still look up, as long as the code is legible.',
  },
  {
    question: 'It says the code is not one we could have printed. What now?',
    answer:
      'Almost always a misread character. The codes never contain the letters I, L, O or U, precisely so they cannot be confused with 1 and 0 — so if you read one of those, try the digit instead. The check built into every code means a wrong entry is rejected rather than quietly returning somebody else\u2019s puzzle.',
  },
  {
    question: 'Can I still get the answers printed in the PDF?',
    answer:
      'Yes, that has not gone anywhere. Leave the answer key switched on in the generator and the solutions come as a section at the back of the document, exactly as before. This page is for when you did not print the key, or no longer have it.',
  },
  {
    question: 'Can I link straight to a solution?',
    answer:
      'Add the code to the address: /sudoku-answers?code=K7M2A9 opens with that puzzle already worked out. Handy if you are setting puzzles for other people and want to hand them the answer separately.',
  },
];
